markdown_extensions:
  - admonition
  - codehilite
  - md_in_html
  - meta
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: true
extra_css:
  - css/code_select.css
plugins:
  - gen-files:
      scripts:
      - docs/gen_ref_pages.py  
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      enable_inventory: true
      handlers:
        python:
          options:
            show_bases: true
            show_source: true
  - search
  - tags
repo_url: https://github.com/madhuravius/trader
site_name: trader
theme:
  features:
    - toc.integrate
  shortcuts: Defines
  icon:
    repo: fontawesome/brands/git-alt
  name: material
  palette:
    primary: grey
