[tool.isort]
profile = "black"

[tool.pyright]
ignore = ["~/.asdf", "./migrations"]
include = ["trader"]
reportMissingImports = true
reportMissingTypeStubs = false
reportUnusedImport = true

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
