[tool.isort]
profile = "black"

[tool.pyright]
ignore = ["~/.asdf", "./migrations"]
include = ["trader"]
reportMissingImports = false
reportMissingTypeStubs = false

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
