name: PEX Builder

on: 
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: https://github.com/actions/checkout@v3
    - uses: https://github.com/actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: make install

    - name: Create PEX File
      run: make pex

    - name: Run trader help command to test file
      run: ./trader.pex --help

    - name: Upload PEX File to Release
      uses: https://gitea.com/actions/release-action@main
      with:
        files: |-
          trader.pex
        api_key: '${{secrets.RELEASE_TOKEN}}'
