name: Tests

on:
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    container:
      image: catthehacker/ubuntu:act-latest
      volumes:
        - /etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt
    steps:
    - uses: https://git.team-z.dev/actions/checkout@v3
    - uses: https://git.team-z.dev/actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: make install

    - name: Run tests
      run: make test
