"""Added ships for starting summary tables

Revision ID: 3b2ee0f4bc99
Revises: 063c8e87b668
Create Date: 2023-10-29 21:40:03.499258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3b2ee0f4bc99'
down_revision: Union[str, None] = '063c8e87b668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ship',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('call_sign', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('faction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('frame_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('waypoint_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ship')
    # ### end Alembic commands ###
