"""Added ship events to print audit log and active events

Revision ID: 44e373441189
Revises: 3b2ee0f4bc99
Create Date: 2023-10-29 22:18:06.267467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '44e373441189'
down_revision: Union[str, None] = '3b2ee0f4bc99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ship_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('event_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('waypoint_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('system_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('credits_earned', sa.Integer(), nullable=True),
    sa.Column('credits_spent', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ship_id'], ['ship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shipevent_created_at'), 'shipevent', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shipevent_created_at'), table_name='shipevent')
    op.drop_table('shipevent')
    # ### end Alembic commands ###
