"""Added shipyard summary information for caching and retrieval purposes

Revision ID: 85517e9af294
Revises: ff2b4fa73b06
Create Date: 2023-11-04 06:14:47.523283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '85517e9af294'
down_revision: Union[str, None] = 'ff2b4fa73b06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shipyardship',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ship_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('supply', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activity', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('purchase_price', sa.Integer(), nullable=False),
    sa.Column('system_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('waypoint_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shipyardtransaction',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ship_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('agent_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('system_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('waypoint_symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shipyardtransaction')
    op.drop_table('shipyardship')
    # ### end Alembic commands ###
