"""Added registration role field for keeping track of ship roles in fleet

Revision ID: bbc651a2dd08
Revises: da1e111fb73b
Create Date: 2023-11-15 08:28:51.836751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bbc651a2dd08'
down_revision: Union[str, None] = 'da1e111fb73b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ship', sa.Column('registration_role', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ship', 'registration_role')
    # ### end Alembic commands ###
