"""Added agent history to keep track of agent statistics

Revision ID: f51f68399840
Revises: 44e373441189
Create Date: 2023-10-29 22:57:44.518802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f51f68399840'
down_revision: Union[str, None] = '44e373441189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agenthistory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('ship_count', sa.Integer(), nullable=False),
    sa.Column('in_system_count', sa.Integer(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenthistory_created_at'), 'agenthistory', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agenthistory_created_at'), table_name='agenthistory')
    op.drop_table('agenthistory')
    # ### end Alembic commands ###
